

// #include<bits/stdc++.h>
// using namespace std ;
// #define ll long long 
// #define fi first
// #define se second
// #define pii pair<int,int>
// bool cmp(pii p1, pii p2){
//     return p1.se<p2.se;
// }
// int main ()
// {

//     int n ;
//     cin>> n;
//     vector<pair<int,int> > v;
//     for(int i=1;i<=n;i++ ){
//         int a, b;
//         cin>>a>>b;
//         v.push_back({a,b});
//     }
//     sort(v.begin(),v.end(),cmp);
//     int last=0;
//     int ans =1;
//     for(int i=1;i<v.size();i++){
//         if(v[last].se<=v[i].fi){
//             last=i;
//             ++ans;
//         }
//     }

//     cout<<ans<<endl;





// }